// Code generated by MockGen. DO NOT EDIT.
// Source: 4dmetaverse/user_db/internal/service (interfaces: LoginDeviceService)

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "4dmetaverse/user_db/internal/entity"
	service "4dmetaverse/user_db/internal/service"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLoginDeviceService is a mock of LoginDeviceService interface.
type MockLoginDeviceService struct {
	ctrl     *gomock.Controller
	recorder *MockLoginDeviceServiceMockRecorder
}

// MockLoginDeviceServiceMockRecorder is the mock recorder for MockLoginDeviceService.
type MockLoginDeviceServiceMockRecorder struct {
	mock *MockLoginDeviceService
}

// NewMockLoginDeviceService creates a new mock instance.
func NewMockLoginDeviceService(ctrl *gomock.Controller) *MockLoginDeviceService {
	mock := &MockLoginDeviceService{ctrl: ctrl}
	mock.recorder = &MockLoginDeviceServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginDeviceService) EXPECT() *MockLoginDeviceServiceMockRecorder {
	return m.recorder
}

// CreateEntity mocks base method.
func (m *MockLoginDeviceService) CreateEntity(arg0 service.LoginDeviceCreateDTO) (*entity.LoginDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEntity", arg0)
	ret0, _ := ret[0].(*entity.LoginDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEntity indicates an expected call of CreateEntity.
func (mr *MockLoginDeviceServiceMockRecorder) CreateEntity(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntity", reflect.TypeOf((*MockLoginDeviceService)(nil).CreateEntity), arg0)
}

// DeleteEntity mocks base method.
func (m *MockLoginDeviceService) DeleteEntity(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEntity", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEntity indicates an expected call of DeleteEntity.
func (mr *MockLoginDeviceServiceMockRecorder) DeleteEntity(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEntity", reflect.TypeOf((*MockLoginDeviceService)(nil).DeleteEntity), arg0)
}

// GetEntitiesBySQL mocks base method.
func (m *MockLoginDeviceService) GetEntitiesBySQL(arg0 string) interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntitiesBySQL", arg0)
	ret0, _ := ret[0].(interface{})
	return ret0
}

// GetEntitiesBySQL indicates an expected call of GetEntitiesBySQL.
func (mr *MockLoginDeviceServiceMockRecorder) GetEntitiesBySQL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntitiesBySQL", reflect.TypeOf((*MockLoginDeviceService)(nil).GetEntitiesBySQL), arg0)
}

// UpdateEntity mocks base method.
func (m *MockLoginDeviceService) UpdateEntity(arg0 string, arg1 service.LoginDeviceUpdateDTO) (*entity.LoginDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEntity", arg0, arg1)
	ret0, _ := ret[0].(*entity.LoginDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEntity indicates an expected call of UpdateEntity.
func (mr *MockLoginDeviceServiceMockRecorder) UpdateEntity(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEntity", reflect.TypeOf((*MockLoginDeviceService)(nil).UpdateEntity), arg0, arg1)
}

// UpdateRefreshTime mocks base method.
func (m *MockLoginDeviceService) UpdateRefreshTime(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRefreshTime", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRefreshTime indicates an expected call of UpdateRefreshTime.
func (mr *MockLoginDeviceServiceMockRecorder) UpdateRefreshTime(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRefreshTime", reflect.TypeOf((*MockLoginDeviceService)(nil).UpdateRefreshTime), arg0)
}
