// Code generated by MockGen. DO NOT EDIT.
// Source: 4dmetaverse/user_db/internal/repository (interfaces: LoginDeviceRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "4dmetaverse/user_db/internal/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockLoginDeviceRepo is a mock of LoginDeviceRepo interface.
type MockLoginDeviceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockLoginDeviceRepoMockRecorder
}

// MockLoginDeviceRepoMockRecorder is the mock recorder for MockLoginDeviceRepo.
type MockLoginDeviceRepoMockRecorder struct {
	mock *MockLoginDeviceRepo
}

// NewMockLoginDeviceRepo creates a new mock instance.
func NewMockLoginDeviceRepo(ctrl *gomock.Controller) *MockLoginDeviceRepo {
	mock := &MockLoginDeviceRepo{ctrl: ctrl}
	mock.recorder = &MockLoginDeviceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoginDeviceRepo) EXPECT() *MockLoginDeviceRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLoginDeviceRepo) Create(arg0 *entity.LoginDevice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLoginDeviceRepoMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLoginDeviceRepo)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockLoginDeviceRepo) Delete(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLoginDeviceRepoMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLoginDeviceRepo)(nil).Delete), arg0)
}

// FindById mocks base method.
func (m *MockLoginDeviceRepo) FindById(arg0 string) (*entity.LoginDevice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", arg0)
	ret0, _ := ret[0].(*entity.LoginDevice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockLoginDeviceRepoMockRecorder) FindById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockLoginDeviceRepo)(nil).FindById), arg0)
}

// FindByNativeSQL mocks base method.
func (m *MockLoginDeviceRepo) FindByNativeSQL(arg0 string) interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNativeSQL", arg0)
	ret0, _ := ret[0].(interface{})
	return ret0
}

// FindByNativeSQL indicates an expected call of FindByNativeSQL.
func (mr *MockLoginDeviceRepoMockRecorder) FindByNativeSQL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNativeSQL", reflect.TypeOf((*MockLoginDeviceRepo)(nil).FindByNativeSQL), arg0)
}

// Update mocks base method.
func (m *MockLoginDeviceRepo) Update(arg0 string, arg1 *entity.LoginDevice) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLoginDeviceRepoMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLoginDeviceRepo)(nil).Update), arg0, arg1)
}
