// Code generated by MockGen. DO NOT EDIT.
// Source: 4dmetaverse/user_db/internal/service (interfaces: VerifySmsService)

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "4dmetaverse/user_db/internal/entity"
	service "4dmetaverse/user_db/internal/service"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockVerifySmsService is a mock of VerifySmsService interface.
type MockVerifySmsService struct {
	ctrl     *gomock.Controller
	recorder *MockVerifySmsServiceMockRecorder
}

// MockVerifySmsServiceMockRecorder is the mock recorder for MockVerifySmsService.
type MockVerifySmsServiceMockRecorder struct {
	mock *MockVerifySmsService
}

// NewMockVerifySmsService creates a new mock instance.
func NewMockVerifySmsService(ctrl *gomock.Controller) *MockVerifySmsService {
	mock := &MockVerifySmsService{ctrl: ctrl}
	mock.recorder = &MockVerifySmsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifySmsService) EXPECT() *MockVerifySmsServiceMockRecorder {
	return m.recorder
}

// CreateEntity mocks base method.
func (m *MockVerifySmsService) CreateEntity(arg0 service.VerifySmsCreateDTO) (*entity.VerifySms, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEntity", arg0)
	ret0, _ := ret[0].(*entity.VerifySms)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEntity indicates an expected call of CreateEntity.
func (mr *MockVerifySmsServiceMockRecorder) CreateEntity(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntity", reflect.TypeOf((*MockVerifySmsService)(nil).CreateEntity), arg0)
}

// GetEntitiesBySQL mocks base method.
func (m *MockVerifySmsService) GetEntitiesBySQL(arg0 string) interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntitiesBySQL", arg0)
	ret0, _ := ret[0].(interface{})
	return ret0
}

// GetEntitiesBySQL indicates an expected call of GetEntitiesBySQL.
func (mr *MockVerifySmsServiceMockRecorder) GetEntitiesBySQL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntitiesBySQL", reflect.TypeOf((*MockVerifySmsService)(nil).GetEntitiesBySQL), arg0)
}

// UpdateCodeUsed mocks base method.
func (m *MockVerifySmsService) UpdateCodeUsed(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCodeUsed", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCodeUsed indicates an expected call of UpdateCodeUsed.
func (mr *MockVerifySmsServiceMockRecorder) UpdateCodeUsed(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCodeUsed", reflect.TypeOf((*MockVerifySmsService)(nil).UpdateCodeUsed), arg0, arg1)
}
