// Code generated by MockGen. DO NOT EDIT.
// Source: 4dmetaverse/main_db/internal/service (interfaces: ShopGroupService)

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "4dmetaverse/main_db/internal/entity"
	service "4dmetaverse/main_db/internal/service"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockShopGroupService is a mock of ShopGroupService interface.
type MockShopGroupService struct {
	ctrl     *gomock.Controller
	recorder *MockShopGroupServiceMockRecorder
}

// MockShopGroupServiceMockRecorder is the mock recorder for MockShopGroupService.
type MockShopGroupServiceMockRecorder struct {
	mock *MockShopGroupService
}

// NewMockShopGroupService creates a new mock instance.
func NewMockShopGroupService(ctrl *gomock.Controller) *MockShopGroupService {
	mock := &MockShopGroupService{ctrl: ctrl}
	mock.recorder = &MockShopGroupServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShopGroupService) EXPECT() *MockShopGroupServiceMockRecorder {
	return m.recorder
}

// CreateEntity mocks base method.
func (m *MockShopGroupService) CreateEntity(arg0 service.ShopGroupCreateDTO) (*entity.ShopGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEntity", arg0)
	ret0, _ := ret[0].(*entity.ShopGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEntity indicates an expected call of CreateEntity.
func (mr *MockShopGroupServiceMockRecorder) CreateEntity(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntity", reflect.TypeOf((*MockShopGroupService)(nil).CreateEntity), arg0)
}

// DeleteEntity mocks base method.
func (m *MockShopGroupService) DeleteEntity(arg0 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEntity", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEntity indicates an expected call of DeleteEntity.
func (mr *MockShopGroupServiceMockRecorder) DeleteEntity(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEntity", reflect.TypeOf((*MockShopGroupService)(nil).DeleteEntity), arg0)
}

// GetEntitiesBySQL mocks base method.
func (m *MockShopGroupService) GetEntitiesBySQL(arg0 string) interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntitiesBySQL", arg0)
	ret0, _ := ret[0].(interface{})
	return ret0
}

// GetEntitiesBySQL indicates an expected call of GetEntitiesBySQL.
func (mr *MockShopGroupServiceMockRecorder) GetEntitiesBySQL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntitiesBySQL", reflect.TypeOf((*MockShopGroupService)(nil).GetEntitiesBySQL), arg0)
}

// UpdateEntity mocks base method.
func (m *MockShopGroupService) UpdateEntity(arg0 uuid.UUID, arg1 service.ShopGroupUpdateDTO) (*entity.ShopGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEntity", arg0, arg1)
	ret0, _ := ret[0].(*entity.ShopGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEntity indicates an expected call of UpdateEntity.
func (mr *MockShopGroupServiceMockRecorder) UpdateEntity(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEntity", reflect.TypeOf((*MockShopGroupService)(nil).UpdateEntity), arg0, arg1)
}
