// Code generated by MockGen. DO NOT EDIT.
// Source: 4dmetaverse/main_db/internal/repository (interfaces: CollectionPoolRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "4dmetaverse/main_db/internal/entity"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCollectionPoolRepo is a mock of CollectionPoolRepo interface.
type MockCollectionPoolRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCollectionPoolRepoMockRecorder
}

// MockCollectionPoolRepoMockRecorder is the mock recorder for MockCollectionPoolRepo.
type MockCollectionPoolRepoMockRecorder struct {
	mock *MockCollectionPoolRepo
}

// NewMockCollectionPoolRepo creates a new mock instance.
func NewMockCollectionPoolRepo(ctrl *gomock.Controller) *MockCollectionPoolRepo {
	mock := &MockCollectionPoolRepo{ctrl: ctrl}
	mock.recorder = &MockCollectionPoolRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCollectionPoolRepo) EXPECT() *MockCollectionPoolRepoMockRecorder {
	return m.recorder
}

// CountCollection mocks base method.
func (m *MockCollectionPoolRepo) CountCollection(arg0 uint64) int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountCollection", arg0)
	ret0, _ := ret[0].(int64)
	return ret0
}

// CountCollection indicates an expected call of CountCollection.
func (mr *MockCollectionPoolRepoMockRecorder) CountCollection(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountCollection", reflect.TypeOf((*MockCollectionPoolRepo)(nil).CountCollection), arg0)
}

// Create mocks base method.
func (m *MockCollectionPoolRepo) Create(arg0 *entity.CollectionPool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCollectionPoolRepoMockRecorder) Create(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCollectionPoolRepo)(nil).Create), arg0)
}

// Delete mocks base method.
func (m *MockCollectionPoolRepo) Delete(arg0 uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCollectionPoolRepoMockRecorder) Delete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCollectionPoolRepo)(nil).Delete), arg0)
}

// FindById mocks base method.
func (m *MockCollectionPoolRepo) FindById(arg0 uint64) (*entity.CollectionPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindById", arg0)
	ret0, _ := ret[0].(*entity.CollectionPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindById indicates an expected call of FindById.
func (mr *MockCollectionPoolRepoMockRecorder) FindById(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindById", reflect.TypeOf((*MockCollectionPoolRepo)(nil).FindById), arg0)
}

// FindByNativeSQL mocks base method.
func (m *MockCollectionPoolRepo) FindByNativeSQL(arg0 string) interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByNativeSQL", arg0)
	ret0, _ := ret[0].(interface{})
	return ret0
}

// FindByNativeSQL indicates an expected call of FindByNativeSQL.
func (mr *MockCollectionPoolRepoMockRecorder) FindByNativeSQL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByNativeSQL", reflect.TypeOf((*MockCollectionPoolRepo)(nil).FindByNativeSQL), arg0)
}

// Update mocks base method.
func (m *MockCollectionPoolRepo) Update(arg0 uint64, arg1 *entity.CollectionPool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCollectionPoolRepoMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCollectionPoolRepo)(nil).Update), arg0, arg1)
}
