// Code generated by MockGen. DO NOT EDIT.
// Source: 4dmetaverse/main_db/internal/service (interfaces: PurchaseRecordService)

// Package mocks is a generated GoMock package.
package mocks

import (
	entity "4dmetaverse/main_db/internal/entity"
	service "4dmetaverse/main_db/internal/service"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPurchaseRecordService is a mock of PurchaseRecordService interface.
type MockPurchaseRecordService struct {
	ctrl     *gomock.Controller
	recorder *MockPurchaseRecordServiceMockRecorder
}

// MockPurchaseRecordServiceMockRecorder is the mock recorder for MockPurchaseRecordService.
type MockPurchaseRecordServiceMockRecorder struct {
	mock *MockPurchaseRecordService
}

// NewMockPurchaseRecordService creates a new mock instance.
func NewMockPurchaseRecordService(ctrl *gomock.Controller) *MockPurchaseRecordService {
	mock := &MockPurchaseRecordService{ctrl: ctrl}
	mock.recorder = &MockPurchaseRecordServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPurchaseRecordService) EXPECT() *MockPurchaseRecordServiceMockRecorder {
	return m.recorder
}

// CreateEntity mocks base method.
func (m *MockPurchaseRecordService) CreateEntity(arg0 service.PurchaseRecordCreateDTO) (*entity.PurchaseRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEntity", arg0)
	ret0, _ := ret[0].(*entity.PurchaseRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEntity indicates an expected call of CreateEntity.
func (mr *MockPurchaseRecordServiceMockRecorder) CreateEntity(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntity", reflect.TypeOf((*MockPurchaseRecordService)(nil).CreateEntity), arg0)
}

// GetEntitiesBySQL mocks base method.
func (m *MockPurchaseRecordService) GetEntitiesBySQL(arg0 string) interface{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntitiesBySQL", arg0)
	ret0, _ := ret[0].(interface{})
	return ret0
}

// GetEntitiesBySQL indicates an expected call of GetEntitiesBySQL.
func (mr *MockPurchaseRecordServiceMockRecorder) GetEntitiesBySQL(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntitiesBySQL", reflect.TypeOf((*MockPurchaseRecordService)(nil).GetEntitiesBySQL), arg0)
}
